export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCTS",
  UPDATE_SELECTED_PRODUCT: "UPDATE_SELECTED_PRODUCTS",
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
};
